### ISSUE TITLE
Wanted the steps to run this application in Windows10 System

### ISSUE THREAD

**Issue by PrakashNayak** [xgdsmileboy/GenPat#89]
on Repair getting below exception 
[ERROR] 2021-10-08 17:36:23,511 @JavaFile #readFileToString Illegal input file path : C:\XXXXX\XXXXX\Genpat_Original_code\GenPat\example\src\buggy-version
Exception in thread "main" java.lang.NullPointerException
	at mfix.core.locator.FakeLocator.getLocations(FakeLocator.java:43)
	at mfix.tools.Repair.repair(Repair.java:573)
	at mfix.tools.Repair.repairAPI(Repair.java:703)
	at mfix.Main.main(Main.java:58)

**Comment by xgdsmileboy** [comment]
Hi @PrakashNayak, I did not test it on Windows systems, so I am not sure whether it will encounter any unexpected failures. Linux is recommended to run GenPat. The environment configuration can be found in the README. Thanks.
